[build]
  base    = "US"
  command = "npm run build"
  publish = "US/dist"
  functions = "US/netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
